### ISSUE TITLE
和在ibmcloud上同样的v2的配置在pws上失败

### ISSUE THREAD

**Issue by sollde** [tlmoe/v2fly-cf#5]
我自己注册了pws，然后app也创建成功，运行也成功。两个平台的所有配置都一样，但是就一个成功一个失败，然后试了ws外的h2,tcp都失败，不知道到底是什么原因。然后下面这是pws上的一条日志，其余的都是同样的重复的日志：$appurl - [2020-07-24T12:36:45.730265756Z] "GET /favicon.ico HTTP/1.1" 404 0 0 "$appurl" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" "*.*.*.*:58512" "*.*.*.*:61118" x_forwarded_for:"*.*.*.*, *.*.*.*" x_forwarded_proto:"https" vcap_request_id:"d85ec0be-7f95-4e66-63da-1ddfeedbffaa" response_time:0.006860 gorouter_time:0.000076 app_id:"c1691035-c0ae-47ba-8c81-b4a1c567e438" app_index:"0" x_cf_routererror:"-" x_b3_traceid:"116c09fd9b125e88" x_b3_spanid:"116c09fd9b125e88" x_b3_parentspanid:"-" b3:"116c09fd9b125e88-116c09fd9b125e88"

**Comment by sollde** [comment]
$appurl - [2020-07-24T13:07:33.431754071Z] "GET / HTTP/1.1" 400 0 12 "-" "Go-http-client/1.1" "*.*.*.*:44004" "*.*.*.*:61118" x_forwarded_for:"*.*.*.*, *.*.*.*, *.*.*.*" x_forwarded_proto:"https" vcap_request_id:"fbc3d5c3-1531-4427-403c-f550ea1c613a" response_time:0.011550 gorouter_time:0.000302 app_id:"c1691035-c0ae-47ba-8c81-b4a1c567e438" app_index:"0" x_cf_routererror:"-" x_b3_traceid:"90f2a5835ff0142e" x_b3_spanid:"90f2a5835ff0142e" x_b3_parentspanid:"-" b3:"90f2a5835ff0142e-90f2a5835ff0142e"

**Comment by sollde** [comment]
我在pivotal文档中找到一段话：[`PWS only supports WebSocket Secure connections (wss:) over port 4443, which is a non-standard`](https://docs.run.pivotal.io/release-notes/)，然后我把原来的443端口换成4443就行了，但是这样就不能套cloudflare了。

**Comment by tlmoe** [comment]
PWS可以使用自定义域名。
在org - domains 添加域名 example.com ；
然后在 app的Networking-Routes  添加路由 v234.example.com ；
在cloudflare 添加cname，   v234.example.com -- v234.cfapps.io 。

可用端口8443，tls

**Comment by sollde** [comment]
不用workers，用cdn，然后把端口换成8443，就可以套cloudflare了，来自[这里](http://machbbs.com/hostloc/148445)，就个人使用来说，速度较之前快了不少。
